# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
