# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181128_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='addDate',
        ),
        migrations.AlterField(
            model_name='art',
            name='link',
            field=models.CharField(max_length=512),
        ),
    ]
